name: build-executable

on: [push,workflow_dispatch]

jobs:
 build-linux:
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v4
   - name: Set up Python 3.10
   - uses: setup-python@v5
     with:
      python-version: 3.10
   - name: Dowload Pyinstaller
     run: | 
      python -m pip install --upgrade pip
      pip install pyinstaller
   - name: Build executable
     run: |
      cd $GITHUB_WORKSPACE/BUILDS/
      pyinstaller --onefile --noconsole -n Simple-Counter-Program $GITHUB_WORKSPACE/main.py
   - name: Push changes
   - uses: Minionguyjpro/Push-Action@1.0.0
