name: build-executable

on: [push,workflow_dispatch]

jobs:
 build-linux:
  runs-on: ubuntu-20.04
  steps:
    - uses: sayyid5416/pyinstaller@v1.6.0
      with:
        spec: ./main.py
        options: -F, -w
        exe_path: ./builds
        upload_exe_with_name: linux-build

 build-windows:
  runs-on: windows-latest
  steps:
   - uses: sayyid5416/pyinstaller@v1.6.0
     with:
      spec: ./main.py
      options: -F, -w
      exe_path: ./builds
      upload_exe_with_name: windows-build

 build-macos:
  runs-on: macos-latest
  steps:
   - run: brew update
   - run: brew upgrade
   - uses: sayyid5416/pyinstaller@v1.6.0
     with:
       spec: ./main.py
       options: -F, -w
       exe_path: ./builds
       upload_exe_with_name: macos-build
