name: build-executable

on: [push,workflow_dispatch]

jobs:
 build-linux:
  runs-on: ubuntu-latest
  steps:
    - uses: Martin005/pyinstaller-action@v1.2.0
      with:
        spec: main.py
        options: -F, -w
        exe_path: ./build
        upload_exe_with_name: windows-build