name: build nightly executables
on:
  push:
    paths:
      - 'main.py'
  workflow_dispatch:

jobs:
 build-linux:
  runs-on: ubuntu-20.04
  steps:
    - name: Build Executables
      uses: sayyid5416/pyinstaller@v1.6.0
      with:
        spec: ./main.py
        options: -F, -w
        exe_path: ./builds
        upload_exe_with_name: linux-build
    - name: Delete .spec file
      run: shred -u main.spec
    - name: Delete other build files
      run: rm -rf build/main
    - name: Manage nightly tag
      run: |
          TAG_NAME="nightly"
          # Check if the tag already exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            # If it exists, delete the old tag
            git tag -d "$TAG_NAME"
          fi
          # Create a new tag pointing to the latest commit
          git tag "$TAG_NAME"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Linux build
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: linux-auto-build
        delete-branch: false
        title: Update Linux build
        body: Automated pull request by Github Actions
        labels: build,linux,automerge
        base: main
    - name: Purge Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       expire-in: 0days
        
 build-windows:
  runs-on: windows-latest
  steps:
    - name: Build Executables
      uses: sayyid5416/pyinstaller@v1.6.0
      with:
        spec: ./main.py
        options: -F, -w
        exe_path: ./builds
        upload_exe_with_name: windows-build
    - name: Delete .spec file
      uses: JesseTG/rm@v1.0.0
      with:
          path: main.spec
    - name: Delete other build files
      uses: JesseTG/rm@v1.0.0
      with:
       path: build/main
    - name: Manage nightly tag
      run: |
        TAG_NAME="nightly"
        # Check if the tag already exists
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          # If it exists, delete the old tag
          git tag -d "$TAG_NAME"
        fi
        # Create a new tag pointing to the latest commit
        git tag "$TAG_NAME"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Windows build
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: windows-auto-build
        delete-branch: false
        title: Update Windows build
        body: Automated pull request by Github Actions
        labels: build,windows,automerge
        base: main